language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test -- --coverage 
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - mv build/index.html build/200.html
  - surge --project ./build --domain magic-squares.surge.sh